/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package beranda;

import Menu_Master.anggota;
import Menu_Master.barang;
import Menu_Master.peminjaman;
import Menu_Master.persetujuan_penggunaan;

import java.io.InputStream;
import static java.lang.Thread.sleep;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

import server.UserSession;
import server.koneksi;

public class menu_utama_LABORAN extends javax.swing.JFrame {

    String id = UserSession.get_id();
    String username = UserSession.get_username();
    String nama = UserSession.get_nama();
    String level = UserSession.get_level();
    
   public void tanggal_jam_sekarang(){
        Thread p;
        p = new Thread(){
            public void run(){
                for(;;){
                    
                    Calendar cal = new GregorianCalendar();
           
                    int jam = cal.get(Calendar.HOUR);
                    int menit = cal.get(Calendar.MINUTE);
                    int detik = cal.get(Calendar.SECOND);
                    int AM_PM = cal.get(Calendar.AM_PM);
                    
                    String day_night = "";
                    if(AM_PM == 1)
                    {
                        day_night = "PM";       
                    }
                    else
                    {
                        day_night ="AM";
                    }
                    String waktuu = jam + ":" + menit + ":" + detik + " " + day_night;
                    waktu.setText(waktuu);
                    
                    try{
                        sleep(1000);
                    }catch(InterruptedException ex){
                        Logger.getLogger(menu_utama_LABORAN.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        };
p.start();
}
    public menu_utama_LABORAN() {
        initComponents();
        tabelPenggunaan();
        tabelBarang();
        setLocationRelativeTo(this);
        tanggal();
        tanggal_jam_sekarang();
        
        HOME.setVisible(true);
        DASHBOARD.setVisible(false);
        LABORATORIUM.setVisible(false);
        PERSETUJUAN.setVisible(false);
        LAPORAN.setVisible(false);
        TABEL_BARANG.setVisible(false);
        TABEL_PENGGUNAAN.setVisible(false);
    }

    public void dashLaboran() { 
        tlevel.setText("Staff Laboran");
        tuser.setText(nama); 
    }
      
    public  void tanggal(){            
        Date ys = new Date();
        SimpleDateFormat s = new SimpleDateFormat("dd-MM-yyyy");
        txtTGL2.setText(s.format(ys));
    }
    
    Statement st;
    Connection con = koneksi.getConnection();
    ResultSet rs;
    DefaultComboBoxModel modelc;
    DefaultTableModel model;
    DefaultTableModel model2;
    Calendar kalender = new GregorianCalendar();
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        judul_signin = new javax.swing.JLabel();
        judul_signin3 = new javax.swing.JLabel();
        txtTGL2 = new javax.swing.JLabel();
        waktu = new javax.swing.JLabel();
        exit2 = new javax.swing.JButton();
        dashboard = new javax.swing.JButton();
        laboratorium = new javax.swing.JButton();
        persetujuan = new javax.swing.JButton();
        laporan = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        HOME = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        DASHBOARD = new javax.swing.JPanel();
        B_tampilalat = new javax.swing.JButton();
        B_tampilpenggunaan = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        LABORATORIUM = new javax.swing.JPanel();
        B_Anggota = new javax.swing.JButton();
        B_Barang = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        PERSETUJUAN = new javax.swing.JPanel();
        B_persetujuan_penggunaan = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        LAPORAN = new javax.swing.JPanel();
        B_lap_penggunaan = new javax.swing.JButton();
        B_lap_barang = new javax.swing.JButton();
        B_lap_peminjaman = new javax.swing.JButton();
        B_lap_permintaan = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        TABEL_BARANG = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabel_barang = new javax.swing.JTable();
        cari1 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        TABEL_PENGGUNAAN = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_penggunaan = new javax.swing.JTable();
        cari = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(10, 61, 98));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        judul_signin.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        judul_signin.setForeground(new java.awt.Color(51, 51, 51));
        judul_signin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judul_signin.setText("Aplikasi Persetujuan Laboratorium IPA");

        judul_signin3.setFont(new java.awt.Font("Source Sans Pro", 1, 18)); // NOI18N
        judul_signin3.setForeground(new java.awt.Color(51, 51, 51));
        judul_signin3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judul_signin3.setText("SMA Bhina Dharma");

        txtTGL2.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        txtTGL2.setForeground(new java.awt.Color(51, 51, 51));
        txtTGL2.setText("jLabel8");

        waktu.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        waktu.setForeground(new java.awt.Color(51, 51, 51));
        waktu.setText("jLabel8");

        exit2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        exit2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asd/pixelLab/Baru/icons8-log-out-32.png"))); // NOI18N
        exit2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTGL2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(waktu, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                        .addComponent(judul_signin, javax.swing.GroupLayout.PREFERRED_SIZE, 624, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(110, 110, 110)
                        .addComponent(exit2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(297, 297, 297)
                        .addComponent(judul_signin3, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(judul_signin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTGL2)
                    .addComponent(exit2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(waktu, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(judul_signin3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        dashboard.setBackground(new java.awt.Color(51, 255, 102));
        dashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asd/pixelLab/Baru/photo1656893928-removebg-preview(80).png"))); // NOI18N
        dashboard.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        dashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashboardActionPerformed(evt);
            }
        });

        laboratorium.setBackground(new java.awt.Color(51, 255, 102));
        laboratorium.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asd/pixelLab/Baru/photo1656894071-removebg-preview(80).png"))); // NOI18N
        laboratorium.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        laboratorium.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laboratoriumActionPerformed(evt);
            }
        });

        persetujuan.setBackground(new java.awt.Color(51, 255, 102));
        persetujuan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asd/pixelLab/Baru/Persetujuan-removebg-preview(80).png"))); // NOI18N
        persetujuan.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        persetujuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                persetujuanActionPerformed(evt);
            }
        });

        laporan.setBackground(new java.awt.Color(51, 255, 102));
        laporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asd/pixelLab/Baru/Report-removebg-preview(80).png"))); // NOI18N
        laporan.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        laporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laporanActionPerformed(evt);
            }
        });

        tuser.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        tuser.setForeground(new java.awt.Color(255, 255, 255));
        tuser.setText("Nama User");

        tlevel.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        tlevel.setForeground(new java.awt.Color(255, 255, 255));
        tlevel.setText("tuser");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon skripsi/icons8-user-50 (putih).png"))); // NOI18N

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("PENDATAAN");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("DASHBOARD");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("LAPORAN");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("PERSETUJUAN");

        HOME.setBackground(new java.awt.Color(204, 204, 255));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asd/pixelLab/Baru/atom-computer-icons-clip-art-others-removebg-preview(500).png"))); // NOI18N

        javax.swing.GroupLayout HOMELayout = new javax.swing.GroupLayout(HOME);
        HOME.setLayout(HOMELayout);
        HOMELayout.setHorizontalGroup(
            HOMELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HOMELayout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addComponent(jLabel2)
                .addContainerGap(176, Short.MAX_VALUE))
        );
        HOMELayout.setVerticalGroup(
            HOMELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HOMELayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        DASHBOARD.setBackground(new java.awt.Color(204, 204, 255));

        B_tampilalat.setBackground(new java.awt.Color(51, 255, 102));
        B_tampilalat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asd/pixelLab/Baru/Tampil_Data-removebg-preview(110).png"))); // NOI18N
        B_tampilalat.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        B_tampilalat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_tampilalatActionPerformed(evt);
            }
        });

        B_tampilpenggunaan.setBackground(new java.awt.Color(51, 255, 102));
        B_tampilpenggunaan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asd/pixelLab/Baru/Tampil_Data-removebg-preview(110).png"))); // NOI18N
        B_tampilpenggunaan.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        B_tampilpenggunaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_tampilpenggunaanActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setText("TAMPIL DATA PENGGUNAAN");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel11.setText("ALAT DAN BAHAN");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel12.setText("TAMPIL DATA ALAT DAN BAHAN");

        javax.swing.GroupLayout DASHBOARDLayout = new javax.swing.GroupLayout(DASHBOARD);
        DASHBOARD.setLayout(DASHBOARDLayout);
        DASHBOARDLayout.setHorizontalGroup(
            DASHBOARDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DASHBOARDLayout.createSequentialGroup()
                .addGroup(DASHBOARDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DASHBOARDLayout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(B_tampilalat, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(DASHBOARDLayout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(jLabel12)))
                .addGap(140, 140, 140)
                .addGroup(DASHBOARDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(B_tampilpenggunaan, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(167, Short.MAX_VALUE))
            .addGroup(DASHBOARDLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(198, 198, 198))
        );
        DASHBOARDLayout.setVerticalGroup(
            DASHBOARDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DASHBOARDLayout.createSequentialGroup()
                .addContainerGap(232, Short.MAX_VALUE)
                .addGroup(DASHBOARDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(B_tampilalat, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B_tampilpenggunaan, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DASHBOARDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addGap(166, 166, 166))
        );

        LABORATORIUM.setBackground(new java.awt.Color(204, 204, 255));

        B_Anggota.setBackground(new java.awt.Color(51, 255, 102));
        B_Anggota.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asd/pixelLab/Baru/1-removebg-preview(110).png"))); // NOI18N
        B_Anggota.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        B_Anggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_AnggotaActionPerformed(evt);
            }
        });

        B_Barang.setBackground(new java.awt.Color(51, 255, 102));
        B_Barang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asd/pixelLab/Baru/photo1656946099-removebg-preview(110).png"))); // NOI18N
        B_Barang.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        B_Barang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_BarangActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel13.setText("INPUT DATA ALAT DAN BAHAN");

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel14.setText("INPUT DATA ANGGOTA LAB");

        javax.swing.GroupLayout LABORATORIUMLayout = new javax.swing.GroupLayout(LABORATORIUM);
        LABORATORIUM.setLayout(LABORATORIUMLayout);
        LABORATORIUMLayout.setHorizontalGroup(
            LABORATORIUMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LABORATORIUMLayout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addGroup(LABORATORIUMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(B_Anggota, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGroup(LABORATORIUMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LABORATORIUMLayout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(B_Barang, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(LABORATORIUMLayout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(jLabel13)))
                .addContainerGap(159, Short.MAX_VALUE))
        );
        LABORATORIUMLayout.setVerticalGroup(
            LABORATORIUMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LABORATORIUMLayout.createSequentialGroup()
                .addContainerGap(237, Short.MAX_VALUE)
                .addGroup(LABORATORIUMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(B_Anggota, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B_Barang, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(LABORATORIUMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addGap(184, 184, 184))
        );

        PERSETUJUAN.setBackground(new java.awt.Color(204, 204, 255));

        B_persetujuan_penggunaan.setBackground(new java.awt.Color(51, 255, 102));
        B_persetujuan_penggunaan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asd/pixelLab/Baru/Persetujuan-removebg-preview(110).png"))); // NOI18N
        B_persetujuan_penggunaan.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        B_persetujuan_penggunaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_persetujuan_penggunaanActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel15.setText("PERSETUJUAN PENGGUNAAN");

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel16.setText("ALAT DAN BAHAN");

        javax.swing.GroupLayout PERSETUJUANLayout = new javax.swing.GroupLayout(PERSETUJUAN);
        PERSETUJUAN.setLayout(PERSETUJUANLayout);
        PERSETUJUANLayout.setHorizontalGroup(
            PERSETUJUANLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PERSETUJUANLayout.createSequentialGroup()
                .addContainerGap(324, Short.MAX_VALUE)
                .addGroup(PERSETUJUANLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(B_persetujuan_penggunaan, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PERSETUJUANLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel16)))
                .addGap(319, 319, 319))
        );
        PERSETUJUANLayout.setVerticalGroup(
            PERSETUJUANLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PERSETUJUANLayout.createSequentialGroup()
                .addGap(220, 220, 220)
                .addComponent(B_persetujuan_penggunaan, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addContainerGap(179, Short.MAX_VALUE))
        );

        LAPORAN.setBackground(new java.awt.Color(204, 204, 255));

        B_lap_penggunaan.setBackground(new java.awt.Color(51, 255, 102));
        B_lap_penggunaan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asd/pixelLab/Baru/Report-removebg-preview(110).png"))); // NOI18N
        B_lap_penggunaan.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        B_lap_penggunaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_lap_penggunaanActionPerformed(evt);
            }
        });

        B_lap_barang.setBackground(new java.awt.Color(51, 255, 102));
        B_lap_barang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asd/pixelLab/Baru/Report-removebg-preview(110).png"))); // NOI18N
        B_lap_barang.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        B_lap_barang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_lap_barangActionPerformed(evt);
            }
        });

        B_lap_peminjaman.setBackground(new java.awt.Color(51, 255, 102));
        B_lap_peminjaman.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asd/pixelLab/Baru/Report-removebg-preview(110).png"))); // NOI18N
        B_lap_peminjaman.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        B_lap_peminjaman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_lap_peminjamanActionPerformed(evt);
            }
        });

        B_lap_permintaan.setBackground(new java.awt.Color(51, 255, 102));
        B_lap_permintaan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asd/pixelLab/Baru/Report-removebg-preview(110).png"))); // NOI18N
        B_lap_permintaan.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        B_lap_permintaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_lap_permintaanActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel17.setText("LAPORAN DATA");

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel18.setText("ALAT DAN BAHAN");

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel19.setText("LAPORAN DATA PEMINJAMAN");

        jLabel20.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel20.setText("ALAT DAN BAHAN");

        jLabel21.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel21.setText("LAPORAN DATA PENGGUNAAN");

        jLabel22.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel22.setText("ALAT DAN BAHAN");

        jLabel23.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel23.setText("LAPORAN DATA PERMINTAAN");

        jLabel24.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel24.setText("ALAT DAN BAHAN");

        javax.swing.GroupLayout LAPORANLayout = new javax.swing.GroupLayout(LAPORAN);
        LAPORAN.setLayout(LAPORANLayout);
        LAPORANLayout.setHorizontalGroup(
            LAPORANLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LAPORANLayout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addGroup(LAPORANLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(LAPORANLayout.createSequentialGroup()
                        .addGroup(LAPORANLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(B_lap_barang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(B_lap_penggunaan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(200, 200, 200)
                        .addGroup(LAPORANLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(B_lap_peminjaman, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(B_lap_permintaan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(130, 130, 130))
                    .addGroup(LAPORANLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(LAPORANLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 220, Short.MAX_VALUE)
                        .addGroup(LAPORANLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LAPORANLayout.createSequentialGroup()
                                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(158, 158, 158))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LAPORANLayout.createSequentialGroup()
                                .addGroup(LAPORANLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel23)
                                    .addComponent(jLabel19))
                                .addGap(121, 121, 121))))))
            .addGroup(LAPORANLayout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addGroup(LAPORANLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LAPORANLayout.createSequentialGroup()
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(157, 157, 157))
        );
        LAPORANLayout.setVerticalGroup(
            LAPORANLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LAPORANLayout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addGroup(LAPORANLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LAPORANLayout.createSequentialGroup()
                        .addComponent(B_lap_barang, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel18))
                    .addGroup(LAPORANLayout.createSequentialGroup()
                        .addComponent(B_lap_peminjaman, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel20)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(LAPORANLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(B_lap_permintaan, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(B_lap_penggunaan, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(LAPORANLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LAPORANLayout.createSequentialGroup()
                        .addGroup(LAPORANLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(jLabel23))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel22))
                    .addGroup(LAPORANLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel24)))
                .addGap(66, 66, 66))
        );

        TABEL_BARANG.setBackground(new java.awt.Color(204, 204, 255));

        tabel_barang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tabel_barang);

        cari1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cari1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cari1KeyReleased(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel25.setText("DAFTAR KETERSEDIAAN ALAT DAN BAHAN");

        jLabel27.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel27.setText("Cari Alat / Bahan");

        javax.swing.GroupLayout TABEL_BARANGLayout = new javax.swing.GroupLayout(TABEL_BARANG);
        TABEL_BARANG.setLayout(TABEL_BARANGLayout);
        TABEL_BARANGLayout.setHorizontalGroup(
            TABEL_BARANGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TABEL_BARANGLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TABEL_BARANGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TABEL_BARANGLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel27)
                        .addGap(26, 26, 26)
                        .addComponent(cari1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TABEL_BARANGLayout.createSequentialGroup()
                .addContainerGap(183, Short.MAX_VALUE)
                .addComponent(jLabel25)
                .addGap(137, 137, 137))
        );
        TABEL_BARANGLayout.setVerticalGroup(
            TABEL_BARANGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TABEL_BARANGLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(TABEL_BARANGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cari1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27))
                .addContainerGap())
        );

        TABEL_PENGGUNAAN.setBackground(new java.awt.Color(204, 204, 255));

        jLabel26.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel26.setText("DAFTAR PENGGUNAAN ALAT DAN BAHAN");

        tabel_penggunaan.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tabel_penggunaan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabel_penggunaan);

        cari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cariKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cariKeyReleased(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel28.setText("Cari Penggunaan ");

        javax.swing.GroupLayout TABEL_PENGGUNAANLayout = new javax.swing.GroupLayout(TABEL_PENGGUNAAN);
        TABEL_PENGGUNAAN.setLayout(TABEL_PENGGUNAANLayout);
        TABEL_PENGGUNAANLayout.setHorizontalGroup(
            TABEL_PENGGUNAANLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TABEL_PENGGUNAANLayout.createSequentialGroup()
                .addContainerGap(178, Short.MAX_VALUE)
                .addGroup(TABEL_PENGGUNAANLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TABEL_PENGGUNAANLayout.createSequentialGroup()
                        .addComponent(jLabel28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cari, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TABEL_PENGGUNAANLayout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addGap(162, 162, 162))))
            .addGroup(TABEL_PENGGUNAANLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(TABEL_PENGGUNAANLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 813, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        TABEL_PENGGUNAANLayout.setVerticalGroup(
            TABEL_PENGGUNAANLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TABEL_PENGGUNAANLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 422, Short.MAX_VALUE)
                .addGroup(TABEL_PENGGUNAANLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cari, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28))
                .addContainerGap())
            .addGroup(TABEL_PENGGUNAANLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(TABEL_PENGGUNAANLayout.createSequentialGroup()
                    .addGap(114, 114, 114)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(53, Short.MAX_VALUE)))
        );

        jLayeredPane2.setLayer(HOME, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(DASHBOARD, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(LABORATORIUM, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(PERSETUJUAN, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(LAPORAN, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(TABEL_BARANG, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(TABEL_PENGGUNAAN, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HOME, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(DASHBOARD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(PERSETUJUAN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(LAPORAN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(LABORATORIUM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(TABEL_BARANG, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(TABEL_PENGGUNAAN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HOME, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(DASHBOARD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(PERSETUJUAN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(LAPORAN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(LABORATORIUM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(TABEL_BARANG, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(TABEL_PENGGUNAAN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator1)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(laboratorium, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(20, 20, 20)
                                                .addComponent(jLabel6))
                                            .addComponent(persetujuan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(laporan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(jLabel5)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tuser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tlevel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(10, 10, 10))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(jLabel4))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(jLabel3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(150, 150, 150)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(848, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(tlevel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tuser, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addGap(26, 26, 26)
                        .addComponent(laboratorium, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addGap(27, 27, 27)
                        .addComponent(persetujuan, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(laporan, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addGap(20, 20, 20))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLayeredPane2)
                        .addContainerGap())))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addGap(181, 181, 181)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setBounds(0, 0, 1000, 650);
    }// </editor-fold>//GEN-END:initComponents

    private void exit2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit2ActionPerformed
    if (JOptionPane.showConfirmDialog(null, "Yakin ingin Logout?", "Aplikasi Persetujuan Laboratorium IPA", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            new login.Menu_Login1().setVisible(true);
            this.dispose();
            this.setVisible(false);
        }
    }//GEN-LAST:event_exit2ActionPerformed

    private void laboratoriumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laboratoriumActionPerformed
        HOME.setVisible(false);
        DASHBOARD.setVisible(false);
        LABORATORIUM.setVisible(true);
        PERSETUJUAN.setVisible(false);
        LAPORAN.setVisible(false);
        TABEL_BARANG.setVisible(false);
        TABEL_PENGGUNAAN.setVisible(false);
    }//GEN-LAST:event_laboratoriumActionPerformed

    private void dashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboardActionPerformed
        HOME.setVisible(false);
        DASHBOARD.setVisible(true);
        LABORATORIUM.setVisible(false);
        PERSETUJUAN.setVisible(false);
        LAPORAN.setVisible(false);
        TABEL_BARANG.setVisible(false);
        TABEL_PENGGUNAAN.setVisible(false);                     
    }//GEN-LAST:event_dashboardActionPerformed

    private void persetujuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_persetujuanActionPerformed
        HOME.setVisible(false);
        DASHBOARD.setVisible(false);
        LABORATORIUM.setVisible(false);
        PERSETUJUAN.setVisible(true);
        LAPORAN.setVisible(false);
        TABEL_BARANG.setVisible(false);
        TABEL_PENGGUNAAN.setVisible(false);                   
    }//GEN-LAST:event_persetujuanActionPerformed

    private void laporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laporanActionPerformed
         DASHBOARD.setVisible(false);
        LABORATORIUM.setVisible(false);
        PERSETUJUAN.setVisible(false);
        LAPORAN.setVisible(true);
        TABEL_BARANG.setVisible(false);
        TABEL_PENGGUNAAN.setVisible(false);
    }//GEN-LAST:event_laporanActionPerformed

    private void B_tampilalatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_tampilalatActionPerformed
        TABEL_BARANG.setVisible(true);
        TABEL_PENGGUNAAN.setVisible(false);
        DASHBOARD.setVisible(false);
        LABORATORIUM.setVisible(false);
        PERSETUJUAN.setVisible(false);
        LAPORAN.setVisible(false);
    }//GEN-LAST:event_B_tampilalatActionPerformed

    private void B_tampilpenggunaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_tampilpenggunaanActionPerformed
        TABEL_BARANG.setVisible(false);
        TABEL_PENGGUNAAN.setVisible(true);
        DASHBOARD.setVisible(false);
        LABORATORIUM.setVisible(false);
        PERSETUJUAN.setVisible(false);
        LAPORAN.setVisible(false);
    }//GEN-LAST:event_B_tampilpenggunaanActionPerformed

    private void cari1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cari1KeyPressed
        tabelBarang();
    }//GEN-LAST:event_cari1KeyPressed

    private void cari1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cari1KeyReleased
        tabelBarang();
    }//GEN-LAST:event_cari1KeyReleased

    private void cariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cariKeyPressed
        tabelPenggunaan();
    }//GEN-LAST:event_cariKeyPressed

    private void cariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cariKeyReleased
        tabelPenggunaan();
    }//GEN-LAST:event_cariKeyReleased

    private void B_AnggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_AnggotaActionPerformed
        anggota user = new anggota();
        user.setVisible(true);
        dispose();
    }//GEN-LAST:event_B_AnggotaActionPerformed

    private void B_BarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_BarangActionPerformed
       barang user = new barang();
       user.setVisible(true);
       dispose();
    }//GEN-LAST:event_B_BarangActionPerformed

    private void B_persetujuan_penggunaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_persetujuan_penggunaanActionPerformed
       persetujuan_penggunaan user = new persetujuan_penggunaan();
       user.setVisible(true);
       dispose();
    }//GEN-LAST:event_B_persetujuan_penggunaanActionPerformed

    private void B_lap_barangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_lap_barangActionPerformed
       try{
           InputStream file = getClass().getResourceAsStream("/Menu_Master/lapBARANG.jrxml");
           JasperDesign jasperDesign = JRXmlLoader.load(file);
           JasperReport jasperReport = JasperCompileManager.compileReport(jasperDesign);
           JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, null,koneksi.getConnection());
           JasperViewer.viewReport(jasperPrint,false);
            }catch(Exception ex)
          {
             System.out.println(ex);
            }
    }//GEN-LAST:event_B_lap_barangActionPerformed

    private void B_lap_peminjamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_lap_peminjamanActionPerformed
       try{
           InputStream file = getClass().getResourceAsStream("/Menu_Master/lapPEMINJAMAN.jrxml");
           JasperDesign jasperDesign = JRXmlLoader.load(file);
           JasperReport jasperReport = JasperCompileManager.compileReport(jasperDesign);
           JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, null,koneksi.getConnection());
           JasperViewer.viewReport(jasperPrint,false);
           }catch(Exception ex)
            {
            System.out.println(ex);
            }
    }//GEN-LAST:event_B_lap_peminjamanActionPerformed

    private void B_lap_penggunaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_lap_penggunaanActionPerformed
         try{
             InputStream file = getClass().getResourceAsStream("/Menu_Master/lapPENGGUNAAN.jrxml");
             JasperDesign jasperDesign = JRXmlLoader.load(file);
             JasperReport jasperReport = JasperCompileManager.compileReport(jasperDesign);
             JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, null,koneksi.getConnection());
             JasperViewer.viewReport(jasperPrint,false);
             }catch(Exception ex)
              {
             System.out.println(ex);
              }
    }//GEN-LAST:event_B_lap_penggunaanActionPerformed

    private void B_lap_permintaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_lap_permintaanActionPerformed
        try{
            InputStream file = getClass().getResourceAsStream("/Menu_Master/lapPERMINTAAN.jrxml");
            JasperDesign jasperDesign = JRXmlLoader.load(file);
            JasperReport jasperReport = JasperCompileManager.compileReport(jasperDesign);
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, null,koneksi.getConnection());
            JasperViewer.viewReport(jasperPrint,false);
            }catch(Exception ex)
             {
              System.out.println(ex);
             }
    }//GEN-LAST:event_B_lap_permintaanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu_utama_LABORAN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu_utama_LABORAN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu_utama_LABORAN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu_utama_LABORAN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu_utama_LABORAN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_Anggota;
    private javax.swing.JButton B_Barang;
    private javax.swing.JButton B_lap_barang;
    private javax.swing.JButton B_lap_peminjaman;
    private javax.swing.JButton B_lap_penggunaan;
    private javax.swing.JButton B_lap_permintaan;
    private javax.swing.JButton B_persetujuan_penggunaan;
    private javax.swing.JButton B_tampilalat;
    private javax.swing.JButton B_tampilpenggunaan;
    private javax.swing.JPanel DASHBOARD;
    private javax.swing.JPanel HOME;
    private javax.swing.JPanel LABORATORIUM;
    private javax.swing.JPanel LAPORAN;
    private javax.swing.JPanel PERSETUJUAN;
    private javax.swing.JPanel TABEL_BARANG;
    private javax.swing.JPanel TABEL_PENGGUNAAN;
    private javax.swing.JTextField cari;
    private javax.swing.JTextField cari1;
    private javax.swing.JButton dashboard;
    private javax.swing.JButton exit2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel judul_signin;
    private javax.swing.JLabel judul_signin3;
    private javax.swing.JButton laboratorium;
    private javax.swing.JButton laporan;
    private javax.swing.JButton persetujuan;
    private javax.swing.JTable tabel_barang;
    private javax.swing.JTable tabel_penggunaan;
    public static final javax.swing.JLabel tlevel = new javax.swing.JLabel();
    public static final javax.swing.JLabel tuser = new javax.swing.JLabel();
    private javax.swing.JLabel txtTGL2;
    private javax.swing.JLabel waktu;
    // End of variables declaration//GEN-END:variables

private void tabelPenggunaan() {
        String[] judul = {"ID Penggunaan","ID Peminjaman Ruang","Tgl Penggunaan","Barang","Jumlah Penggunaan","Jenis","Status Barang","Staff Pendamping","Status Permohonan"};
        model2 = new DefaultTableModel(judul,0);
        tabel_penggunaan.setModel(model2);
        String sql = "SELECT * FROM penggunaan where id_penggunaan like '%"+cari.getText()+"%' or nm_barang like '%"+cari.getText()+"%'";
        try {
            rs = con.createStatement().executeQuery(sql);
            while(rs.next()) {
               String id = rs.getString("id_penggunaan");
               String idpinjam = rs.getString("id_peminjaman");
               String tgl = rs.getString("tgl_pelaksanaan");
               String nama = rs.getString("nm_barang");
               String jml = rs.getString("jumlah");
               String JENIS = rs.getString("jenis");
               String stat = rs.getString("status_barang");
               String staf = rs.getString("staff");
               String status = rs.getString("status_permohonan");
               String[] data = {id,idpinjam,tgl,nama,jml,JENIS,stat,staf,status};
               model2.addRow(data);
           }
        }catch(Exception e) {
           System.out.println(e);
        }
    }

     private void tabelBarang() {
        String[] judul = {"Kode Barang","Nama","Jenis Barang","Tgl Input","Jumlah","Penyimpanan","Status Barang"};
        model = new DefaultTableModel(judul,0);
        tabel_barang.setModel(model);
        String sql = "SELECT * FROM barang where kd_barang like '%"+cari1.getText()+"%' or nm_barang like '%"+cari1.getText()+"%'";
        try {
            rs = con.createStatement().executeQuery(sql);
            while(rs.next()) {
               String kode = rs.getString("kd_barang");
               String nama = rs.getString("nm_barang");
               String jenis = rs.getString("jenis");
               String tgl = rs.getString("tgl_input");
               String jml = rs.getString("jumlah");
               String rak = rs.getString("penyimpanan");
               String STAT = rs.getString("status");
               String[] data = {kode,nama,jenis,tgl,jml,rak,STAT};
               model.addRow(data);
           }
        }catch(Exception e) {
           System.out.println(e);
        }
    }
   
}
